name: common_widgets
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/BwesShr/common_widgets

environment:
  sdk: '>=2.19.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  awesome_icons: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: 
